### ISSUE TITLE
fibonacci-python container struck on Gem5. 

### ISSUE THREAD

**Issue by Prithvi-Velicheti** [vhive-serverless/vSwarm-u#119]
Hi I am running vswarm functions on Gem5. fibonacci-go and fibonacci-nodejs ran well. But fibonacci-python was strucking at this point. 

Also,
![tmux_fibpy](https://github.com/vhive-serverless/vSwarm-u/assets/25413124/f1aa7956-9861-4c6a-87fc-cf039720f9f4)
 can we have multiple functions together on Gem5, instead of pinning one function to the core each time ?

**Comment by dhschall** [comment]
Just to understand this is while you run the gem5 setup procedure or the qemu setup?
Did the qemu setup succeed for Fibonacci-python? You can check this in the $(WORKING_DIR)/install.log file.

**Comment by Prithvi-Velicheti** [comment]
prithvi@odysseus:vSwarm-u$ make -f simulation/Makefile install_check
echo "Tryed to install 9 functions. 9 installed and tested successful"
Tryed to install 9 functions. 9 installed and tested successful
==================
 Install successful
================== 
prithvi@odysseus:vSwarm-u$ cat wkdir/functions.list 
fibonacci-go
fibonacci-nodejs
fibonacci-python
aes-go
aes-nodejs
aes-python
auth-go
auth-nodejs
auth-python


They seem to be fine David. I will try once again. Sorry for your time. I appreciate it.

**Comment by Prithvi-Velicheti** [comment]
They seem to be fine David. I will cancel simulation once again and try. Thanks for your time, I appreciate your efforts. 
![fibpy](https://github.com/vhive-serverless/vSwarm-u/assets/25413124/59bfb2d5-ed15-4b73-88f6-38de68d2b62b)

**Comment by Prithvi-Velicheti** [comment]
Hi David, for some reason for your given gem5 all the python functions ( aes-python, fib, auth) are failing. I tried to upgrade the version of Gem5 and checking now. Got this error. Did you ever see something like this. 
![error](https://github.com/vhive-serverless/vSwarm-u/assets/25413124/a9b593c7-6b07-4d1f-a32d-e03cae28c025)

**Comment by Prithvi-Velicheti** [comment]
Hi @dhschall the issue could be closed. Somehow with the existing Gem5 (from vswarm-u repo), all the python functions ( aes, Fibonacci, auth) are failing. 

Changed the gem5 variant and tried again. It's working. Had to slightly modify gem5init and rebuild the disk though. Thanks for all the detailed instructions in the quick start guide.
