### ISSUE TITLE
skylake dumping 0 stats.  Hi when I am running skylake config, by changing default system=skylake in run_sim.py , it is not dumping any stats. 

### ISSUE THREAD

**Issue by Prithvi-Velicheti** [vhive-serverless/vSwarm-u#120]
prithvi@odysseus:fibonacci-nodejs$ ../../../scripts/cpi.sh stats.txt
Insts:	0
Cycles:	12404479
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted

**Comment by dhschall** [comment]
Hi, the cpi.sh script doesn't work for the skylake config. as the O3 core uses different keys to print the statistics for instructions.
However, you can simply modify the script.
Change this line:
https://github.com/vhive-serverless/vSwarm-u/blob/264d626cf9c7687cb4d8af5601ec587f2e017ae9/scripts/cpi.sh#L3C1-L3C73

**Comment by Prithvi-Velicheti** [comment]
Thanks David will let you know.
