### ISSUE TITLE
Wrong Golang address in setup script

### ISSUE THREAD

**Issue by reza-alimadadi** [vhive-serverless/vSwarm-u#123]
Hi
GoLang installation has a problem in `setup/setup_host.sh` line 102:
First the link directory doesn't exist and it should be changed to `https://go.dev/dl/${GO_BUILD}.tar.gz`
Second on variable `GO_VERSION` you should add revision.

Thank you

**Comment by dhschall** [comment]
Hi, thank you for letting me know!
Does #125 fix the problem?

**Comment by reza-alimadadi** [comment]
Yes, thank you.
