### ISSUE TITLE
RuntimeError: New CPU (system.cpu0) is already active

### ISSUE THREAD

**Issue by zhewenhu** [vhive-serverless/vSwarm-u#53]
I am following the quick start and tried to run `./sim_function.sh fibonacci-go results/`, but then I got the following error, how should I solve it?

 11: Stop client
Switch to kvm core
switching cpus
RuntimeError: New CPU (system.cpu0) is already active.

At:
  build/X86/python/m5/simulate.py(288): switchCpus
  /home/zhewen/vSwarm-u/gem5utils/systems/simple/system.py(143): switchToKvmCpus
  run_sim.py(163): executeM5FailCode
  run_sim.py(186): simulate
  run_sim.py(243): <module>
  build/X86/python/m5/main.py(442): main
build/X86/cpu/kvm/base.cc:570: hack: Pretending totalOps is equivalent to totalInsts()

**Comment by dhschall** [comment]
This error occurs when you want to switch from detailed core to the kvm core but you have never switched to the detailed core before.
Can you check the logs if the there is an preceeding cpu switch to detailed core?

**Comment by zhewenhu** [comment]
> This error occurs when you want to switch from detailed core to the kvm core but you have never switched to the detailed core before. Can you check the logs if the there is an preceeding cpu switch to detailed core?

No, it starts with KVM and never switched to detailed core.

**Comment by ustiugov** [comment]
@dhschall any update on this? anything else that the user needs to supply?

**Comment by dhschall** [comment]
Hey, sorry. Somehow I don't get notifications from github properly at the moment. :( 
Ok so when it does not switch it is probably something with the test-client.
I know there was change in gem5 from version v21 to v22 that might have caused the problem.
However, I just merged some major updates with several improvements that also should fix this issue.
Can you please pull the latest changes and build gem5 again with the `setup/gem5.Makefile`

Note that now the workflow has slightly changed but it makes everything much more stable.

**Comment by dhschall** [comment]
Let me know if it works and Ill try to keep up to date
