### ISSUE TITLE
PerfKvmCounter::attach failed (2)

### ISSUE THREAD

**Issue by AtlasKY** [vhive-serverless/vSwarm-u#82]
Hi,

I've been trying to setup and run some simulations following the documentation. Everything seems to be working until when I try to setup the functions.

When I run `./setup_function.sh` in wkdir, I get this output:
`+ GEM5=/home/atlas/vSwarm-u/resources//gem5/build/X86/gem5.opt
+ KERNEL=kernel
+ DISK_IMAGE=disk.img
+ GEM5_CONFIG=run_sim.py
+ sudo chown atlas /dev/kvm
+ FN=fibonacci-go
+ RESULTS_DIR=results
+ OUTDIR=results/fibonacci-go/
+ mkdir -p results/fibonacci-go/
+ sudo /home/atlas/vSwarm-u/resources//gem5/build/X86/gem5.opt --outdir=results/fibonacci-go/ run_sim.py --kernel kernel --disk disk.img --function fibo
gem5 Simulator System.  https://www.gem5.org
gem5 is copyrighted software; use the --copyright option for details.

gem5 version 22.0.0.1
gem5 compiled Jan  9 2023 16:21:40
gem5 started Jan  9 2023 19:59:21
gem5 executing on Thesis-x86, pid 1590
command line: /home/atlas/vSwarm-u/resources//gem5/build/X86/gem5.opt --outdir=results/fibonacci-go/ run_sim.py --kernel kernel --disk disk.img --functi

/home/atlas/vSwarm-u
Create CPU:  X86KvmCPU
Created CPU: 2x X86KvmCPU, Mem mode: atomic_noncaching
--- Setup Mode ---
Global frequency set at 1000000000000 ticks per second
warn: system.workload.acpi_description_table_pointer.rsdt adopting orphan SimObject param 'entries'
warn: failed to generate dot output from results/fibonacci-go/config.dot
build/X86/sim/kernel_workload.cc:46: info: kernel located at: kernel
      0: system.pc.south_bridge.cmos.rtc: Real-time clock set to Sun Jan  1 00:00:00 2012
system.pc.com_1.device: Listening for connections on port 3456
0: system.remote_gdb: listening for remote gdb on port 7000
build/X86/mem/coherent_xbar.cc:140: warn: CoherentXBar system.llc_bus has no snooping ports attached!
build/X86/dev/intel_8254_timer.cc:128: warn: Reading current count from inactive timer.
Start simulation...
build/X86/cpu/kvm/base.cc:150: info: KVM: Coalesced MMIO disabled by config.
build/X86/arch/x86/cpuid.cc:180: warn: x86 cpuid family 0x0000: unimplemented function 2
build/X86/arch/x86/cpuid.cc:180: warn: x86 cpuid family 0x0000: unimplemented function 3
build/X86/arch/x86/cpuid.cc:180: warn: x86 cpuid family 0x0000: unimplemented function 4
build/X86/arch/x86/cpuid.cc:180: warn: x86 cpuid family 0x0000: unimplemented function 5
build/X86/arch/x86/cpuid.cc:180: warn: x86 cpuid family 0x0000: unimplemented function 6
build/X86/arch/x86/cpuid.cc:180: warn: x86 cpuid family 0x0000: unimplemented function 8
build/X86/cpu/kvm/base.cc:150: info: KVM: Coalesced MMIO disabled by config.
build/X86/arch/x86/cpuid.cc:180: warn: x86 cpuid family 0x0000: unimplemented function 2
build/X86/arch/x86/cpuid.cc:180: warn: x86 cpuid family 0x0000: unimplemented function 3
build/X86/arch/x86/cpuid.cc:180: warn: x86 cpuid family 0x0000: unimplemented function 4
build/X86/arch/x86/cpuid.cc:180: warn: x86 cpuid family 0x0000: unimplemented function 5
build/X86/arch/x86/cpuid.cc:180: warn: x86 cpuid family 0x0000: unimplemented function 6
build/X86/arch/x86/cpuid.cc:180: warn: x86 cpuid family 0x0000: unimplemented function 8
build/X86/sim/simulate.cc:194: info: Entering event queue @ 0.  Starting simulation...
build/X86/cpu/kvm/perfevent.cc:183: panic: PerfKvmCounter::attach failed (2)
Memory Usage: 2390716 KBytes
build/X86/cpu/kvm/perfevent.cc:183: panic: PerfKvmCounter::attach failed (2)
Memory Usage: 2390716 KBytes
Program aborted at tick 0
./setup_function.sh: line 57:  1589 Aborted`

I'd appreciate any help you could provide!

Thanks,
Atlas

**Comment by dhschall** [comment]
Hi @AtlasKY 
Thank you very much for your interest and the question.

Two ideas for debugging your problem

Can you check with
`sudo kvm-ok` if kvm is working correctly?
You might need to install the cpu-checker according to [here](https://linuxhint.com/install_kvm_ubuntu/)
Furthermore, can you make sure you run kvm as root (sudo)?

**Comment by AtlasKY** [comment]
Hi,

I think I found the issue.

I've been trying to run vSwarm-u on cloud VMs. It seems the KvmCPU requires access to performance counters to instantiate a timer and other functionalities, however the hypervisor of the commercial cloud provider does not allow access to those counters. Hence, the file not found error (2) for PerfKvmAttach. This was true for Azure VMs, I've found AWS EC2 does not allow 2nd level virtualisation so Kvm just does not work there to begin with, either. 

I'm going to try with a bare metal machine now, if the issue persists, I'll come back here :)

Atlas

**Comment by dhschall** [comment]
Hi @AtlasKY 
That's true. I encountered the same problems a while ago. GCR and maybe also AWS seems to give access to nested virtualisation but gem5 seems to need some very restricted access to performance counters.
I was also never able to run it on those clouds
